### ISSUE TITLE
Issue with server response

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/RFShowcase-NodeRed-Redis-v1#11]
We are waiting too long for server response, up to 2+ minutes:
![qqq6](https://user-images.githubusercontent.com/40596171/60973041-19e97a00-a330-11e9-880c-707d1d720db4.png)

**Comment by kuvakina** [comment]
And after reload, it doesn't show info (but we have info for this user):
![qqq7](https://user-images.githubusercontent.com/40596171/60973479-07237500-a331-11e9-8a4f-a8a980144e73.png)

**Comment by kuvakina** [comment]
We'd need Dmytro's help with this task

**Comment by kuvakina** [comment]
I've created 5th Medications row and reload the page: and see only 4 rows. When I create a new issue for this heading again, it started to behave strange again. And also I can't create more than 4 rows

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 

This issue was fixed. 

The problem was in flows: before a few synopses were connected to one flow at the same time and that triggered pending error and loading for synopses. 

To fix this error, the flow was added to Subflow and now each synopsis connect to Subflow separately and error don't appear:
![qqq6.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/b1b60775-88a8-44e0-8621-84e8bf8bf0e9)

**Note:** in Subflow lies original (one) flow, so each synopsis connects to the same flow but separately, not at the same time :
![qqq7.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/12c68b5c-1809-4757-aff1-65f3ec35cf88)

**Comment by PhilBarrett** [comment]
Great work, thank you
