### ISSUE TITLE
Update of the flow erase all data

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/RFShowcase-NodeRed-Redis-v1#12]
We noticed, that at some point all data on server (headings, users) are being erased. As we learned, the reason is that when we update the flow all the data deletes. Could Dmytro take a look, as this behavior isn't correct

**Comment by tony-shannon** [comment]
ok well spotted, so the problem afaik is that the data isnt being persisted in redis between flow deployments

**Comment by kuvakina** [comment]
Could be, @tony-shannon Would be good if Dmytro can look into it

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett 
this issue was solved: we applied changes, that Dmytro suggested:  to enable "appendfsync always" instead of "appendfsync everysec"
