### ISSUE TITLE
change source from "etherCIS" to "redis"

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/RFShowcase-NodeRed-Redis-v1#2]
As we arent using ethercis here yet

**Comment by kuvakina** [comment]
@tony-shannon this was changed:
![aaa1](https://user-images.githubusercontent.com/40596171/60897673-26f36400-a271-11e9-98c0-5e2f5d0ca583.png)
![aaa2](https://user-images.githubusercontent.com/40596171/60897674-26f36400-a271-11e9-927b-2b67188cccae.png)
![aaa3](https://user-images.githubusercontent.com/40596171/60897676-26f36400-a271-11e9-81fe-2590ed8ca0fa.png)
![aaa4](https://user-images.githubusercontent.com/40596171/60897677-278bfa80-a271-11e9-9acc-a8b3d1900db1.png)

**Comment by PhilBarrett** [comment]
Reviewed and closing as working.
