### ISSUE TITLE
Check transform capability..

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/RFShowcase-NodeRed-Redis-v1#5]
Once the system is running, please check that allergies are available using the transform functionality. 

The test nodes show how the transforms are invoked, ie /allergy? transform=allergyUI2openehr

**Comment by tony-shannon** [comment]
Should be testable via browser or postman

**Comment by kuvakina** [comment]
@tony-shannon due to issues with server couldn't check yet. Problem described in related issue #11

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett we checked it and it works now. There was a problem with date type/format: it should be Timestamp Value, like "1562771460954"

**Comment by tony-shannon** [comment]
can you please show this working in action please @kuvakina

**Comment by kuvakina** [comment]
@tony-shannon here you can see that it's working:
1) http://nodered-showcase.ripple.foundation:1880/patient/3339558600/allergies/vfecpkw1elcgkdsyn67y5
![qqq5.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/0fdff0df-20fe-4e05-a4ab-a77a9f662743)

2) http://nodered-showcase.ripple.foundation:1880/patient/3339558600/allergies/vfecpkw1elcgkdsyn67y5?transform=TransformB-Allergy-UI2FHIR
![qqq6.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/606d2c90-ba7a-4c89-9ae2-e50a63514eb1)

**Comment by tony-shannon** [comment]
Great to see that transform capability in action
thank you,
