### ISSUE TITLE
Error handling issue

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/RFShowcase-NodeRed-Redis-v1#9]
- [x] 1) when we search for the patient and there is no such patient, we should see "No Records found". But we see this error message, that isn't good:
![qqq3](https://user-images.githubusercontent.com/40596171/60964684-9a05e480-a31c-11e9-880b-1fb4f2243ed8.png)

- [x] 2) The patient doesn't have info. What we go to Problems/Medications/Allergies page we should see "No Records found". But instead we see this error popup:
![qqq2](https://user-images.githubusercontent.com/40596171/60964761-dc2f2600-a31c-11e9-8ff2-ad70670212b8.png)

**Comment by kuvakina** [comment]
@tony-shannon @PhilBarrett Bogdan changed messages for both searches:
1) 
![qqq8](https://user-images.githubusercontent.com/40596171/60975463-ba419d80-a334-11e9-908a-c2a208b57898.png)

2) The error popup, that patient doesn't have headings, was removed, please see the video: https://drive.google.com/file/d/1QOTGkWMmDcObl9j5xVEI_D2kCErvxnQS/view

**Comment by PhilBarrett** [comment]
Looks much better. Can we ensure consistency though

Summary screen instead of 'no data' should say 'No records found'

Also for problems/medications/allergies and vitals it shows 'No Records found' instead of 'No records found' Capitalised R

**Comment by kuvakina** [comment]
@PhilBarrett Bogdan managed to fix search patient, see the video please: https://drive.google.com/file/d/1eFLjX_4c9JeNKQO47TqcRsP6xjAYvZIR/view


this is also done:
>Summary screen instead of 'no data' should say 'No records found'
Also for problems/medications/allergies and vitals it shows 'No Records found' instead of 'No records found' Capitalised R

![qqq10.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/9ba3edaf-7fb9-4eb7-a0c9-31d2ee5fc814)
![qqq11.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/cb7616cb-68cc-4a67-9fde-67ef9b6ccad9)
